"""Regenerate the projects catalog block in README.md.

Pulls the public repo list from the GitHub API, groups repos using a static
category mapping, and writes a markdown table for each category between the
``<!-- PROJECTS:START -->`` and ``<!-- PROJECTS:END -->`` markers.

Run from the repo root:

    GH_USER=AhmedTAlZahrani python scripts/update_readme.py

The workflow at .github/workflows/update-profile.yml runs this on
workflow_dispatch and commits the result as github-actions[bot].
"""
import os
import sys
from pathlib import Path

import requests

GH_USER = os.environ.get("GH_USER", "AhmedTAlZahrani")
GH_TOKEN = os.environ.get("GITHUB_TOKEN")  # optional; raises rate limit

README_PATH = Path(__file__).resolve().parent.parent / "README.md"
START_MARKER = "<!-- PROJECTS:START -->"
END_MARKER = "<!-- PROJECTS:END -->"
PROFILE_REPO_NAME = "AhmedTAlzahrani"  # don't include the profile repo itself

CATEGORIES = {
    "Saudi Transport & Infrastructure": [
        "saudi-road-crash-severity-predictor",
        "riyadh-metro-ridership-forecaster",
        "riyadh-bus-network-optimizer",
        "saudi-logistics-hub-classifier",
        "sar-freight-delay-pipeline",
        "saudi-crash-hotspot-realtime-tracker",
        "saudi-transport-data-platform",
    ],
    "NEOM Smart City": [
        "neom-autonomous-fleet-simulator",
        "neom-energy-grid-anomaly-detector",
        "neom-resident-mobility-recommender",
    ],
    "ML & Data Science": [
        "customer-churn-ml-pipeline",
        "chest-xray-pneumonia-cnn",
        "nlp-sentiment-topic-engine",
        "energy-demand-forecaster",
        "superstore-sales-analytics",
        "ai-market-sentiment-analyzer",
        "smoking-cessation-causal-effects",
    ],
    "Early Projects": [
        "Green-Mobility-Impact-Analyzer",
        "traffic-congestion-analyzer",
        "freight-bottleneck-analyzer",
        "urban-traffic-congestion-predictor",
    ],
}


def fetch_repos():
    headers = {"Accept": "application/vnd.github+json"}
    if GH_TOKEN:
        headers["Authorization"] = f"Bearer {GH_TOKEN}"
    url = f"https://api.github.com/users/{GH_USER}/repos"
    params = {"per_page": 100, "type": "public", "sort": "full_name"}
    resp = requests.get(url, headers=headers, params=params, timeout=30)
    resp.raise_for_status()
    return resp.json()


def render_row(repo):
    name = repo["name"]
    url = f"https://github.com/{GH_USER}/{name}"
    desc = (repo.get("description") or "").strip() or "—"
    return f"| [{name}]({url}) | {desc} |"


def render_table(repos):
    if not repos:
        return ""
    lines = ["| Project | Description |", "|---------|-------------|"]
    lines.extend(render_row(r) for r in repos)
    return "\n".join(lines)


def build_block(repos):
    by_name = {r["name"]: r for r in repos}
    used = set()
    sections = []

    for category, names in CATEGORIES.items():
        rows = [by_name[n] for n in names if n in by_name]
        used.update(r["name"] for r in rows)
        if rows:
            sections.append(f"### {category}\n\n{render_table(rows)}")

    leftover = [
        r for r in repos
        if r["name"] not in used
        and r["name"] != PROFILE_REPO_NAME
        and not r.get("fork")
        and not r.get("archived")
    ]
    if leftover:
        leftover.sort(key=lambda r: r["name"].lower())
        sections.append(f"### Other\n\n{render_table(leftover)}")

    return "\n\n".join(sections)


def splice(readme_text, new_block):
    start = readme_text.index(START_MARKER) + len(START_MARKER)
    end = readme_text.index(END_MARKER)
    header = (
        "\n<!-- Auto-generated by .github/workflows/update-profile.yml"
        " - do not edit by hand -->\n\n"
    )
    return readme_text[:start] + header + new_block + "\n\n" + readme_text[end:]


def main():
    repos = fetch_repos()
    repos = [r for r in repos if not r.get("fork") and not r.get("archived")]
    repos = [r for r in repos if r["name"] != PROFILE_REPO_NAME]

    print(f"fetched {len(repos)} public repos for {GH_USER}", file=sys.stderr)
    for category, names in CATEGORIES.items():
        present = [n for n in names if any(r["name"] == n for r in repos)]
        print(f"  {category}: {len(present)}/{len(names)}", file=sys.stderr)

    block = build_block(repos)
    readme_text = README_PATH.read_text(encoding="utf-8")
    new_text = splice(readme_text, block)

    if new_text == readme_text:
        print("no changes", file=sys.stderr)
        return

    README_PATH.write_text(new_text, encoding="utf-8")
    print(f"wrote {README_PATH}", file=sys.stderr)


if __name__ == "__main__":
    main()
